    drop table restaurant if exists;
    drop table review if exists;
    drop table user if exists;
 
    create table restaurant (
        id bigint generated by default as identity,
        address varchar(100) not null,
        city varchar(50) not null,
        logo_uri varchar(50) not null,
        name varchar(50) not null,
        phone_number varchar(50) not null,
        uri varchar(100) not null,
        primary key (id)
    );
 
    create table review (
        id bigint generated by default as identity,
        date_created timestamp not null,
        rating integer not null,
        text varchar(140) not null,
        restaurant_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );
 
    create table user (
        id bigint generated by default as identity,
        email varchar(50) not null,
        first_name varchar(50) not null,
        last_name varchar(50) not null,
        password varchar(76) not null,
        primary key (id)
    );

    alter table review 
        add constraint FK70ry7cuti298yxet366rynxch 
        foreign key (restaurant_id) 
        references restaurant;

    alter table review 
        add constraint FKiyf57dy48lyiftdrf7y87rnxi 
        foreign key (user_id) 
        references user;